### PR TITLE
Finding the beginning node in a circular linked list

### PR DESCRIPTION
**Pull request by GargNikitaa**

### CODE REVIEW

**Comment by RitamPaul** [comment]
Your code is not running. try to debug it. In c language there is no oops so i guess public, private, class will not work. Make your program in c++ language

**Comment by GargNikitaa** [comment]
Yes this program is for C++ language itself.

**Comment by RitamPaul** [comment]
Yes, but in c++ also it is not running. I think those " * " should not be there inside STRUCT

**Comment by GargNikitaa** [comment]
Oh Got it. Have made the changes pls have a look

**Pull request merged**
