### PR TITLE
Added Binary Search implementation in C++

### PR DESCRIPTION
**Pull request by Akashdeep-k**
Binary Search Code

### CODE REVIEW

**Comment by RitamPaul** [comment]
brother just add a condition when the user entered element will not be present in the array and add a condition so that user can run the programme till he/she need. Basically make it a menu driven programme

**Comment by RitamPaul** [comment]
just add a readme file for basic introduction of the programme and library used

**Comment by Akashdeep-k** [comment]
I have explained the code by adding the comments.
Tell me if anything needs to be updated.

**Comment by RitamPaul** [comment]
Yes buddy you have done everything but don't write the introduction inside your programme. Just create a readme.txt file which will contain introduction part. So, all you need to do -> create a folder with name of your prograamme -> inside the folder, upload your original code of c++ -> in the same folder create a readme.txt file containing the introduction, basic, library used

**Pull request merged**
