### PR TITLE
remove_punctuation added

### PR DESCRIPTION
**Pull request by 11-yashasvi**

### CODE REVIEW

**Comment by RitamPaul** [comment]
just add the + symbol so that punctuations as well as mathematic symbols will perform the same

**Comment by 11-yashasvi** [comment]
> just add the + symbol so that punctuations as well as mathematic symbols will perform the same

>Sir changes done.

**Comment by 11-yashasvi** [comment]
Sir changes done.

**Comment by RitamPaul** [comment]
Dear, just add a little few more things = name, Programme name, date created at the begining of the programme, leave a blank line after every code line and use some hashtag comments in python to indicate what is happening after which line to make the whole project more than 25 lines. Then your project will be successfully merged

**Comment by RitamPaul** [comment]
any updates ?

**Pull request merged**
